[package]
name = "blockboard"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
cosmwasm-schema = "^1.5"
cosmwasm-std = "^1.5"
cw-storage-plus = "^1.2"
schemars = "^0.8"
serde = { version = "^1", default-features = false, features = ["derive"] }
thiserror = "^1"

[dev-dependencies]
cw-multi-test = "^0.20"
